# https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139
language: go

go:
#  - 1.7
#  - 1.8
  - 1.9
  - master

install: true

services:
  - redis-server
  - mysql
  - mongodb

test:
  adapter: mysql2
  database: golang_test
  username: travis
  encoding: utf8

#addons:
#  apt:
#    sources:
#      - mysql-5.7-trusty
#    packages:
#      - mysql-server
#      - mysql-client

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: master
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

notifications:
  email: false

before_script:
  - go env
  - bash ./bash/go_get_dependency.sh
  - bash ./bash/go_get_dependency_govendor.sh
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

##  Mysql 5.7
#  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
#  - sudo service mysql restart

script:
#  - bash ./bash/formatted.sh
  - bash ./bash/test.sh
#  - bash ./bash/check_code.sh
  - bash ./bash/codecov.sh
  - bash ./bash/goverage.sh
#  - bash ./bash/benchmark.sh

after_success:
  - bash ./bash/goveralls.sh
  - bash <(curl -s https://codecov.io/bash)
  - godacov -t $CODACY_TOKEN -r ./coverage.out -c $TRAVIS_COMMIT

branches:
  only:
    - dev
